# https://docs.docker.com/compose/profiles/

services:
  praw_streaming:
    image: tap:praw_python
    build:
      context: ./praw-python
      dockerfile: Dockerfile
    container_name: praw_streaming
    volumes:
      - ./dataset:/usr/src/app/dataset
      - ./praw-python/bin:/usr/src/app/bin
      - ./.env:/usr/src/app/bin/.env
    networks:
      - tap
    #        command: ["-m", "streaming", "-a", "http://logstash:8081", "-t", "1", "--do-not-save"]
    command: ["-m", "streaming", "-a", "http://logstash:8081", "-t", "1"]
    profiles: ["ingestion", "streaming", "pipeline"]
    depends_on:
      topic:
        condition: service_completed_successfully
      kafkaServer:
        condition: service_started

  sendn:
    image: tap:praw_python
    build:
      context: ./praw-python
      dockerfile: Dockerfile
    container_name: sendn
    volumes:
      - ./dataset:/usr/src/app/dataset
      - ./praw-python/bin:/usr/src/app/bin
      - ./.env:/usr/src/app/bin/.env

    networks:
      - tap
    command:
      ["-m", "sendn", "-n", "500", "-a", "http://logstash:8081", "-t", "5"]
    profiles: ["sendn"]
    depends_on:
      logstash:
        condition: service_healthy
      topic:
        condition: service_completed_successfully

  download_dataset:
    image: tap:praw_python
    build:
      context: ./praw-python
      dockerfile: Dockerfile
    container_name: download_dataset
    volumes:
      - ./dataset:/usr/src/app/dataset
      - ./praw-python/bin:/usr/src/app/bin
      - ./.env:/usr/src/app/bin/.env
      - ocr_model:/root/.EasyOCR/
      - captioning_model:/tmp
    networks:
      - tap
    command: ["-m", "downloadn", "-n", "500"]
    profiles: ["download-dataset"]

  es_settings:
    image: tap:es_settings_python
    build:
      context: ./es_settings_python
      dockerfile: Dockerfile
    container_name: es_settings
    volumes:
      - ./es_settings_python/bin:/usr/src/app/bin
    networks:
      - tap
    profiles: ["pipeline", "elasticsearch"]
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - 8081:8081
    networks:
      tap:
        ipv4_address: 10.0.100.24
    environment:
      XPACK_MONITORING_ENABLED: "false"
      #LOG_LEVEL: "debug"
    volumes:
      - ./logstash/pipeline/reddit.conf:/usr/share/logstash/pipeline/logstash.conf

    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
    profiles: ["logstash", "ingestion", "pipeline"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1 GB
    networks:
      - tap
    volumes:
      - es_data:/usr/share/elasticsearch/data
    profiles: ["elasticsearch", "pipeline"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 30s
      retries: 3

  kibana:
    hostname: kibana
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      topic:
        condition: service_completed_successfully
    networks:
      - tap
    profiles: ["kibana", "pipeline"]

networks:
  tap:
    name: meme_pipeline
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.100.0/24
# https://docs.docker.com/reference/compose-file/volumes/
volumes:
  es_data:
